# Generated by Django 5.0.1 on 2024-03-18 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest', models.IntegerField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='search',
            name='guest',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.guest'),
        ),
    ]
