# Generated by Django 5.0.1 on 2024-03-18 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_guest_alter_search_guest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='guest',
            new_name='GuestNumber',
        ),
    ]
