# Generated by Django 5.0.1 on 2024-02-11 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_staffmodel_enddate_alter_staffmodel_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmodel',
            name='Image',
            field=models.ImageField(null=True, upload_to='home/StaffImg/'),
        ),
    ]
