# Generated by Django 5.0.1 on 2024-02-11 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_staffmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmodel',
            name='Image',
            field=models.ImageField(default='', upload_to='images/Staff'),
        ),
    ]
