# Generated by Django 5.0.1 on 2024-03-18 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_guest_guest_guestnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='GuestNumber',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
