# Generated by Django 5.0.1 on 2024-03-18 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_guest_guestnumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='search',
            old_name='guest',
            new_name='Guest',
        ),
    ]
