# Generated by Django 5.0.1 on 2024-03-21 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_guest_search_guest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='checkin',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='checkout',
            field=models.DateField(null=True),
        ),
    ]
