# Generated by Django 5.0.1 on 2024-02-13 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_staffmodel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roommodel',
            name='RoomType',
        ),
        migrations.RemoveField(
            model_name='roommodel',
            name='Users',
        ),
        migrations.RemoveField(
            model_name='usersmodel',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='usersmodel',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='staffmodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='RoomTypeModel',
        ),
        migrations.DeleteModel(
            name='RoomModel',
        ),
        migrations.DeleteModel(
            name='UsersModel',
        ),
    ]
